
name: Auto Merge

on:
  workflow_run:
    # workflows: [ "Workflow Main" ]
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.ZUBAIRGITHUBTOKEN }}"
          MERGE_LABELS: ""
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "5000"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_COMMIT_MESSAGE: pull-request-title
